version: '3.8'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: your_username
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: your_db
    ports:
      - "5432:5432"
    volumes:
      - ./sql/01_init.sql:/docker-entrypoint-initdb.d/01_init.sql
  
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
